# Generated by Django 5.2.14 on 2026-07-01 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_email', models.TextField()),
                ('course', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('deadline', models.DateTimeField()),
                ('weight_marks', models.IntegerField(blank=True, null=True)),
                ('priority_score', models.IntegerField(default=0)),
                ('estimated_hours', models.IntegerField(blank=True, null=True)),
                ('requirements', models.JSONField(default=list)),
                ('subtasks', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
