# Generated by Django 5.2.14 on 2026-06-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_stripe_customer_id_assingments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assingments',
            name='implimentation',
            field=models.JSONField(default=list),
        ),
    ]
